<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Nilai_ijazah_model extends CI_Model
{

    public $table = 'nilai_ijazah';
    // public $id = 'id';
    public $id = 'id_nilai_ijazah';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_csid($csid)
    {
        $this->db->where('id_calon_siswa', $csid);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('nisn', $q);
        $this->db->or_like('nilai_bhs_indo', $q);
        $this->db->or_like('nilai_bhs_inggris', $q);
        $this->db->or_like('nilai_ipa', $q);
        $this->db->or_like('nilai_ips', $q);
        $this->db->or_like('nilai_mtk', $q);
        $this->db->or_like('nilai_akhir', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('id_user', $q);
        $this->db->or_like('nisn', $q);
        $this->db->or_like('nilai_bhs_indo', $q);
        $this->db->or_like('nilai_bhs_inggris', $q);
        $this->db->or_like('nilai_ipa', $q);
        $this->db->or_like('nilai_ips', $q);
        $this->db->or_like('nilai_mtk', $q);
        $this->db->or_like('nilai_akhir', $q);
        $this->db->or_like('keterangan', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Nilai_ijazah_model.php */
/* Location: ./application/models/Nilai_ijazah_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-09-07 23:43:13 */
/* http://harviacode.com */