<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pengumuman_pendaftaran_model extends CI_Model
{

    public $table = 'pengumuman_pendaftaran';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->select('pp.*, ta.tahun_ajaran');
        $this->db->from($this->table . ' pp');
        $this->db->order_by($this->id, $this->order);
        $this->db->join('tahun_ajaran ta', 'ta.id=pp.id_tahun_ajaran', 'left');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('judul', $q);
        $this->db->or_like('deskripsi', $q);
        $this->db->or_like('id_tahun_ajaran', $q);
        $this->db->or_like('tgl_update', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->select('pp.*, ta.id as ta_id, ta.tahun_ajaran');
        $this->db->from($this->table . ' pp');
        $this->db->join('tahun_ajaran ta', 'ta.id=pp.id_tahun_ajaran', 'left');
        $this->db->order_by('pp.' . $this->id, $this->order);
        $this->db->like('pp.id', $q);
        $this->db->or_like('pp.judul', $q);
        $this->db->or_like('pp.deskripsi', $q);
        $this->db->or_like('pp.id_tahun_ajaran', $q);
        $this->db->or_like('pp.tgl_update', $q);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pengumuman_pendaftaran_model.php */
/* Location: ./application/models/Pengumuman_pendaftaran_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-09-07 23:51:37 */
/* http://harviacode.com */